sonar.projectKey=afnan-and-neball_Library-Management-System
sonar.organization=afnan-and-neball
sonar.host.url=https://sonarcloud.io

# Coverage report path
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
